name: Sync and Merge XSD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: destination
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout CCMM source
        uses: actions/checkout@v4
        with:
          repository: techlib/CCMM
          path: source

      # 1. Nastavení Pythonu
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 2. Instalace knihoven
      - name: Install dependencies
        run: |
          pip install lxml click

      # 3. Kopírování XSD souborů s pročištěním
      - name: Copy XSD directories
        run: |
          if [ -d "destination/mirror-ccmm" ]; then
            rm -rf destination/mirror-ccmm/*
          else
            mkdir -p destination/mirror-ccmm
          fi
          
          cd source
          find . -name "*.xsd" > xsd_list.txt
          if [ -s xsd_list.txt ]; then
            
            cat xsd_list.txt | xargs cp --parents -t ../destination/mirror-ccmm/
            echo "Kopírování dokončeno."
          else
            echo "Varování: Žádné XSD soubory nebyly nalezeny!"
            exit 1
          fi
      # 4. Spuštění Python skriptu
      - name: Run merge_schemas.py
        run: |
          cd destination
          python merge_schemas.py mirror-ccmm/ ccmm_merged.xsd

      # 5. Commit a Push
      - name: Commit and push
        run: |
          cd destination
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync and merge XSD schemas"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
