name: Generate CCMM diagram

on:
  push:
    branches:
      - main
    paths:
      - 'flattenCCMM/ccmm_merged.xsd'
      - 'ceCCMM/ccmm-xsd-vis.py'
  workflow_dispatch:

jobs:
  build-diagram:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 1. sousteni skriptu
      
      - name: Generate PlantUML source
        run: |
          python ceCCMM/ccmm-xsd-vis.py > diagram.puml

      # 2. renderovani do png
      - name: Render PlantUML to PNG
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -tpng diagram.puml

      # 3. Commit a Push
      - name: Commit and Push diagram
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add diagram.png
          git commit -m "docs: automatická aktualizace diagramu [skip ci]" || exit 0
          git push
